# Generated by Django 5.2.7 on 2025-10-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
