# Generated by Django 5.2.7 on 2025-10-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0002_initial'),
        ('users', '0003_organization_description_organization_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionpoint',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_points', to='users.organization', verbose_name='Организация, обрабатывающая точку'),
        ),
    ]
