# Generated by Django 5.2.7 on 2025-10-30 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution', '0003_pollutionpoint_handled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutionpoint',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pollutionpoint',
            name='cleaned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата очистки'),
        ),
        migrations.AddField(
            model_name='pollutionpoint',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работ'),
        ),
        migrations.AlterField(
            model_name='pollutionpoint',
            name='pollution_type',
            field=models.CharField(choices=[('trash', 'Бытовой мусор'), ('oil', 'Нефтяное пятно'), ('industrial', 'Промышленные отходы'), ('chemical', 'Химикаты'), ('plastic', 'Пластик'), ('other', 'Другое')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pollutionpoint',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pollution_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
